language: r
cache: packages
pandoc_version: 2.3.1

addons:
  apt:
    packages:
    - cargo
    - libpoppler-cpp-dev
    - libmagick++-dev
    - asymptote

services:
  - xvfb

script:
  - xvfb-run -a make gitbook
  - ./_deploy.sh
